spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grc_db?useSSL=false&serverTimezone=UTC
    username: grc_user
    password: grc_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: myVeryStrongJwtSecretKeyExample1234567890
  expirationMs: 86400000 # 24 hours in milliseconds

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
